### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(ZZZApp)
add_subdirectory(ZZZAppContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    UntitledProject3plugin
    ZZZAppContentplugin)